inchworm:
  joint_state_controller:
    publish_rate: 50
    type: joint_state_controller/JointStateController

  position_trajectory_controller:
    type: "effort_controllers/JointTrajectoryController"
    joints:
      - iw_ankle_foot_bottom
      - iw_beam_ankle_bottom
      - iw_mid_joint
      - iw_beam_ankle_top
      - iw_ankle_foot_top

    gains:
      iw_ankle_foot_bottom: {p: 1.5, i: 0, d: 0.01}
      iw_beam_ankle_bottom: {p: 150.0, i: 0, d: 1}
      iw_mid_joint: {p: 150.0, i: 0, d: 1}
      iw_beam_ankle_top: {p: 150.0, i: 0, d: 1}
      iw_ankle_foot_top: {p: 1.5, i: 0, d: 0.01}

    constraints:
      iw_ankle_foot_bottom:
        goal: 0.025
      iw_beam_ankle_bottom:
        goal: 0.025
      iw_mid_joint:
        goal: 0.025
      iw_beam_ankle_top:
        goal: 0.025
      iw_ankle_foot_top:
        goal: 0.025

  