inchworm:
  joint_effort_controller_joint_1':
    joint: joint_1'
    pid:
      d: 10.0
      i: 0.01
      p: 100.0
    type: effort_controllers/JointPositionController
  joint_effort_controller_joint_2:
    joint: joint_2
    pid:
      d: 10.0
      i: 0.01
      p: 100.0
    type: effort_controllers/JointPositionController
  joint_effort_controller_joint_3:
    joint: joint_3
    pid:
      d: 10.0
      i: 0.01
      p: 100.0
    type: effort_controllers/JointPositionController
  joint_state_controller:
    publish_rate: 100
    type: joint_state_controller/JointStateController
