controller_list:
  - name: fake_ltr_controller
    type: $(arg execution_type)
    joints:
      - link1_to_foot
      - link2_to_link1
      - link3_to_link2
      - link3_to_link4
      - link4_to_foot
  - name: fake_rtl_controller
    type: $(arg execution_type)
    joints:
      - link1_to_foot
      - link2_to_link1
      - link3_to_link2
      - link3_to_link4
      - link4_to_foot
initial:  # Define initial robot poses.
  - group: ltr
    pose: no_torque