# Simulation settings for using moveit_sim_controllers
moveit_sim_hw_interface:
  joint_model_group: ltr
  joint_model_group_pose: no_torque
# Settings for ros_control_boilerplate control loop
generic_hw_control_loop:
  loop_hz: 300
  cycle_time_error_threshold: 0.01
# Settings for ros_control hardware interface
hardware_interface:
  joints:
    - link1_to_foot
    - link2_to_link1
    - link3_to_link2
    - link3_to_link4
    - link4_to_foot
  sim_control_mode: 1  # 0: position, 1: velocity
# Publish all joint states
# Creates the /joint_states topic necessary in ROS
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50
controller_list:
  - name: /inchworm/arm_controller
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
      - link1_to_foot
      - link2_to_link1
      - link3_to_link2
      - link3_to_link4
      - link4_to_foot