inchworm_hw_interface:
  joints:
    - j0
    - j1
    - j2
    - j3
    - j4

# joint_state_controller is not needed, since the serial_msg_interface directly publishes JointState
# joint_state_controller:
#   type: joint_state_controller/JointStateController

position_trajectory_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - j0
    - j1
    - j2
    - j3
    - j4
  # TOLERANCE:
  constraints:
    goal_time: 5.0
    j0:
      trajectory: 0.02
      goal: 0.01
    j1:
      trajectory: 0.02
      goal: 0.01
    j3:
      trajectory: 0.02
      goal: 0.01
    j4:
      trajectory: 0.02
      goal: 0.01
    j5:
      trajectory: 0.02
      goal: 0.01